const caixaPrincipal = document.querySelector(".caixa-principal");
const caixaPerguntas = document.querySelector(".caixa-perguntas");
const caixaAlternativas = document.querySelector(".caixa-alternativas");
const caixaResultado = document.querySelector('.caixa-resultado');
const textoResultdo = document.querySelector(".texto-resultado");
    const perguntas = [
    {
        enunciado: "Insira o enunciado da Perguntas 1" ,
        alternativas: ["Alternativa 1" , "Alternativas 2"] ,
    },
    {
        enunciado: "Insira o enunciado da Perguntas 2" ,
        alternativas: ["Alternativa 1" , "Alternativas 2"] ,
    },
    {
        enunciado: "Insira o enunciado da Perguntas 3" ,
        alternativas: ["Alternativa 1" , "Alternativas 2"] ,
    }
    ];
